s = set()
n= input("Enter the No:")
s.add(int(n))
n= input("Enter the No:")
s.add(int(n))
n= input("Enter the No:")
s.add(int(n))
n= input("Enter the No:")
s.add(int(n))
n= input("Enter the No:")
s.add(int(n))
n= input("Enter the No:")
s.add(int(n))
n= input("Enter the No:")
s.add(int(n))
n= input("Enter the No:")
s.add(int(n))
print(s)